[redis]
host = "127.0.0.1"
port = 6379
database = 1

[postgres]
host = "127.0.0.1"
port = 6969
user = "postgres"
password = "postgres"
db_name = "postgres"
db_schema = "no_orm"
min_connections = 10
max_connections = 20
